---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "YOUR NAME"
pagetitle: "PM1 YOUR NAME"

format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin
---

::: {.callout-important collapse=true}
## Memo format

Like all other submissions for this course, we expect the memo to be **neat and well organized**.

A memo is a short, polished report. Meaning, it should be well written and thoughtfully laid out. Some neatness and organizational hints/tips (not an exhaustive list):

- There should be absolutely no code in your report --- don’t hide it; code should not be visible/accessible.
- Include a date indicating when report was created.
- There should be no tibbles/data frames or raw R output --- should use tables (avoid unnecessarily long output)!
- Any plots or graphics should be polished (appropriate labels and/or captions).
- All figures and tables should be properly labeled and referenced --- must make use of quarto cross-referencing.
- Should use heading and sub-headings appropriately.
- Remove prompts and instructions meant to assist students.
- Should include a link to project’s GitHub repo.
- GitHub repo should be well organized and have a few commits (no templates, commit of most recent work)


:::

::: {.callout-warning collapse=true}
GitHub (free account) cannot store large files. If you try to commit and push a large dataset you will have an ERROR! Any file over 100 MB (100,000 KB) needs to be added to the `.gitignore` file BEFORE committing.

**We may need to do that for files in your final project!**
:::


::: {.callout-tip icon=false}

## Github Repo Link

To link to your github **repo**sitory, appropriately edit the example link below. Meaning replace `https://your-github-repo-url` with your github repo url. Suggest verifying the link works before submitting.

[https://your-github-repo-url](https://your-github-repo-url)

:::


## Data source

Blah blah blah^[where blah blah came from, an example of footnote]

## Why this data

Blah blah blah^[another footnote]

## Data quality & complexity check

Blah blah blah

## Potential data issues

Blah blah blah

## Misc

Blah Blah
